site_name: PSD - Docs
site_description: Getting Started with Docker
site_author: Alexander Martinez Fajardo
site_url: https://squidfunk.github.io/mkdocs-material/

# Repository
repo_name: alex00pep/dosing-site-tech-overview
repo_url: https://github.com/alex00pep/dosing-site-tech-overview
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2020 Alexander Martinez Fajardo'

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png

extra_css:
  - css/styles.css
  - css/dark-mode.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - meta
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dockersamples
      repo: 101-tutorial
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list

# Page tree
nav:
  - Getting Started: pages/index.md
  - Goals and milestones: pages/milestones.md
  - Technical requirements: pages/reqs.md
  - Our application: pages/app.md
  - User interface Prototypes: pages/ui.md
  - Browser support: pages/browser.md
  - Persisting our data: pages/db.md
  - Deploying our application to Cloud: pages/cloud.md
  - Agreement for billing and maintenance costs: pages/billing.md
  - License: pages/license.md